linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - unnecessary_new
    - prefer_final_fields
    - always_declare_return_types
    - annotate_overrides
    - public_member_api_docs
    - lines_longer_than_80_chars
    - prefer_single_quotes
    - avoid_types_on_closure_parameters
    - unnecessary_this
    - prefer_is_empty
    - use_key_in_widget_constructors