name: barbell_calculator
description: A Flutter project for calculating barbell weights and managing plate inventory.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.0.0
  in_app_purchase: ^3.0.0
  shared_preferences: ^2.0.0
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

  web:
    favicon: web/favicon.png
    icons:
      - web/icons/Icon-192.png
      - web/icons/Icon-512.png